# Generated by Django 4.2 on 2024-02-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Modal",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "title",
                    models.CharField(
                        blank=True, db_column="title", max_length=200, null=True
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, db_column="content", max_length=2048, null=True
                    ),
                ),
            ],
            options={
                "db_table": "modal",
                "managed": True,
            },
        ),
    ]
