# Generated by Django 4.2 on 2024-02-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modal",
            name="content",
            field=models.TextField(blank=True, db_column="content", null=True),
        ),
    ]
