# Generated by Django 5.1.4 on 2024-12-10 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_alter_modal_content"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Modal",
        ),
    ]
